### ISSUE TITLE
Aplikacja nie działa po zmianach na stronie Tauron Elicznik

### ISSUE THREAD

**Issue by maverick8189** [manio/elicznik-rs#1]
Hej,
Po zmianach na stronie Elicznik aplikacja nie pobiera danych z csv.
Czy jest szansa na dostosowanie kodu pod obecną stronę?
Zmiany które zauważyłem:
![image](https://user-images.githubusercontent.com/94139840/211559511-7dc4e1a9-2acf-4dae-af7d-227f3df4e08f.png)
![image](https://user-images.githubusercontent.com/94139840/211559388-8a61b797-c376-4358-9772-f1a722b90e94.png)

**Comment by manio** [comment]
Dzięki za info. Faktycznie jest problem: wczoraj jeszcze wykonało się poprawnie a dzisiaj już błąd.
Jak znajdę chwilę to muszę to rozpracować... pytanie tylko czy to nie są jakieś ich chwilowe problemy techniczne...

Z tego co widzę to jeszcze nikt (z bliźniaczych projektów) na to nie zareagował...

**Comment by manio** [comment]
*Update*: zmiany na szybko:
```diff
diff --git a/src/scraper.rs b/src/scraper.rs
index edfec10..17c8413 100644
--- a/src/scraper.rs
+++ b/src/scraper.rs
@@ -3,7 +3,7 @@ use std::collections::HashMap;
 use std::time::Instant;
 
 static URL: &str = "https://logowanie.tauron-dystrybucja.pl/login";
-static CHART_URL: &str = "https://elicznik.tauron-dystrybucja.pl/index/charts";
+static CHART_URL: &str = "https://elicznik.tauron-dystrybucja.pl/energia/do/dane";
 static SERVICE: &str = "https://elicznik.tauron-dystrybucja.pl";
 
 pub struct Scraper {
@@ -25,13 +25,13 @@ impl Scraper {
 
         //chart data parameters
         let mut params = HashMap::new();
-        params.insert("dane[paramType]", "csv");
-        params.insert("dane[trybCSV]", "godzin");
-        params.insert("dane[startDay]", &self.start_date);
+        params.insert("form[fileType]", "CSV");
+        params.insert("form[type]", "godzin");
+        params.insert("form[from]", "01.01.2023");
         if let Some(date) = &self.end_date {
-            params.insert("dane[endDay]", &date);
+            params.insert("form[to]", &date);
         }
-        params.insert("dane[checkOZE]", "on");
+        params.insert("form[consum]", "1");
 
         //creating client with cookie store
         let client = reqwest::Client::builder().cookie_store(true).build()?;
```

powodują jedynie wyplucie pustego CSV z nagłówkiem:
```Data; Wartość kWh;Rodzaj;```

**Comment by manio** [comment]
Update: wymagane były wszystkie parametry i teraz dostaję CSV z danymi ale to nie jest JSON którego się spodziewałem (on był generowany do produkowania wykresu na stronie)...
Muszę nad tym jeszcze popracować...

**Comment by maverick8189** [comment]
Jakie jeszcze parametry są wymagane? Ja mam na razie zablokowane konto w Tauronie przez zbyt dużą liczbę zapytań więc nie mogę przetestować. Z tego co zauważyłem wczoraj to csv wygenerowany na stronie Elicznika sam w sobie był nieprawidłowy, pojawiały się krzaki w nagłówkach i zamiast daty z ostatniej godziny był ciąg cyfr. Zgłosiłem to do Tauronu. Natomiast raport generowany w formacie xml był prawidłowo sformatowany.

**Comment by manio** [comment]
Jedyna zmiana ponad to, co w powyższym patchu - to zawsze trzeba było dodawać parametr `form[to]` (wcześniej jak tego parametru brakowało to Tauron z tego co pamiętam przyjmował domyślnie do daty bieżącej). No i w wyniku dostaję takiego CSV:
```
Data; Wartość kWh;Rodzaj;
01.01.2023 1:00;0.645;pobór;
01.01.2023 2:00;0.707;pobór;
01.01.2023 3:00;0.613;pobór;
01.01.2023 4:00;0.639;pobór;
01.01.2023 5:00;0.713;pobór;
01.01.2023 6:00;0.733;pobór;
01.01.2023 7:00;0.886;pobór;
01.01.2023 8:00;0.799;pobór;
01.01.2023 9:00;0.677;pobór;
[...]
```

**Comment by manio** [comment]
No to sobie podziałałem ;)
```
Przekroczono maksymalną ilość dopuszczalnych logowań na konto.
Informujemy, że odnotowaliśmy przekroczenie liczby możliwych logowań na Twoje konto, dlatego zostało ono tymczasowo zablokowane.
Dostęp zostanie automatycznie odblokowany po ośmiu godzinach.
Próby logowania się przed tym terminem będą powodowały wydłużenie okresu blokady o kolejne 8 godzin.
W przypadku pytań lub uwag, dotyczących opisanej sytuacji, prosimy o kontakt z naszymi Biurami Obsługi Klienta lub infolinią.
```

**Comment by manio** [comment]
Update:
@PiotrMachowski odwalił kawał dobrej roboty:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/72
Zmiany w gałęzi:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/tree/dev

**Comment by maverick8189** [comment]
To prawda. Sam korzystam z jego integracji. Tylko brakuje mi właśnie historii zużycia stąd potrzeba skorzystania z Twojej aplikacji. Piotr pobiera tylko aktualne wartości wskazań licznika więc nie musi parsować csv.

**Comment by PiotrMachowski** [comment]
Akszuali, to dane godzinne można pobrać w JSONie korzystając z API dla wykresów (czyli tego samego, co ja). Wtedy nie trzeba się bawić z csv

**Comment by manio** [comment]
Aby usystematyzować - ja to do tej pory pobierałem dane właśnie w JSONIE (z tego samego URL co Ty - czyli z `.../index/charts`. Chodzi generalnie o to że te dane były w JSON ale przygotowywane tym samym mechanizmem, który generuje CSV (ja to przynajmniej tak rozumiem). Potwierdza to chociażby fakt że przekazywałem parametr `dane[trybCSV] = 'godzin'` w POST.
Ten JSON wynikowy miał nieco inną strukturę (był inaczej opakowany/zagnieżdżony) w porównaniu do tego co Ty, Piotrze parsujesz w swoim projekcie, co jednak nie zmienia faktu że był to JSON.

Mam teraz dwie drogi - albo parsować "prawdziwego" CSV albo zmodyfikować parser i generować podobne JSONy, które ty używasz (jak rozumiem te same które są do generowania wykresu w JS oraz w aplikacji mobilnej).
Troche szkoda że ten CSV nie ma już tej postaci rozdzielonej na pobór/oddanie energii - ale wszystko jest zbilansowane do jednej wartości (godzinowo) z informacją czy to pobranie czy oddanie. Bo wlasnie na podstawie generacji miałem fajne porównanie z moją właściwą produkcją z falownika. W tym CSV tego nie ma, w JSON jest ale tylko "po nowemu".

**Comment by manio** [comment]
Generując tego CSV bezpośrednio ze strony jednak mam produkcję i pobranie rozdzielone :)
Robiłem to wcześniej z linka `.../energia/do/dane` i to mnie zmyliło... bo tamten CSV był taki jak pisałem wyżej.

**Comment by manio** [comment]
Tak jak pisałem tu: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/72#issuecomment-1378276079 "w bambuko" robiła mnie poprzednia wersja serwisu :)

Mimo wszystko skłaniam się ku rozwiązaniu CSV zamiast JSON bo myślę że to będzie bardziej stabilne rozwiązanie na przyszłość - mam nadzieje że nie będą z tym za dużo "czarować" i ma to wydaje się większe perspektywy - a te JSONy to wydaje mi sie ze wieksza szansa że znowu coś zmienią/zaktualizują - np. przy aktualizacji aplikacji dla androida.
W zasadzie w tej wersji aktualnej tego CSV mam wszystko co do tej pory wyciągałem JSON-em - czyli produkcję godzinową dla każdej doby.

@maverick8189 
Stworzyłem testowego branch-a w którym pociągam CSV (narazie parametry na sztywno od pierwszego grudnia do wczoraj). Proszę Cię o test czy u Ciebie wychodzi dobry CSV - uruchom to proszę np. w taki sposób:
```bash
git pull
git checkout testy-csv
cargo run -- --start '2022-12-01' --output wynik.csv
```
I daj znać czy ten wynik.csv zawiera sensowne dane dla Ciebie (zarówno produkcja jak i konsumpcja).
Jeśli bedzie OK to przepiszę ten parser z JSON-a na CSV i w ten sposób program znowu będzie działał jak do tej pory.

**Comment by maverick8189** [comment]
Cześć, zaraz przetestuję i dam znać

**Comment by maverick8189** [comment]
U mnie csv wygląda tak;
![image](https://user-images.githubusercontent.com/94139840/211814452-33694d31-fb05-4c2d-a51a-cba33f85aa27.png)
Nie wiem czym to jest spowodowane, jak pobieram ręcznie ze strony to wygląda tak samo, krzaki w nagłówkach i brak daty dla ostatniej godziny danego dnia. A w formacie xlsx jest prawidłowo.
U Ciebie csv wygląda normalnie?

**Comment by maverick8189** [comment]
Update: Co do poprzedniego to nevermind. To Excel na Windows robi taki śmietnik. Sprawdziłem w Notepad++ i dodatkowo na moim serwerze Linuxowym i csv jest prawidłowy :)

**Comment by manio** [comment]
Tak - to excel. Ok, dzięki za test.
Myślę że poprawię to aby korzystał z tego nowego API i JSON-a ale dodatkowo później zrobię też metodę CSV aby była jakaś alternatywa w razie czego...
_stay tuned_ :)

**Comment by manio** [comment]
Ok... w końcu naprawione (wymagało to troche wiecej czasu ze względu na obsługę plików JSON do których można zapisywać oraz z nich czytać).
Zrobiłem dodatkowe testy potwierdzające jakość pobieranych danych - wygląda to dobrze.
Na próbkę 984 wpisów (pobieranych od 1 grudnia) wszystkie się zgadzały z tym co było w starym API i poprzednich JSONach. Dopisał jedynie 49 nowych z ostatnich dwóch dni, których nie było, w tym także jeden nowy z 12 grudnia (gdzie brakowało godziny 24-tej).
Wobec powyższego temat nowego API JSON-a uznaję za zamkięty :)
Dzięki @maverick8189 za zgłoszenie i testy.

Myślę że fajna wartość dodana to by było to przetwarzanie również tego CSV tą alternatywną metodą - ale skoro to działa to narazie ma niższy priorytet... :]

**Comment by manio** [comment]
> Myślę że fajna wartość dodana to by było to przetwarzanie również tego CSV tą alternatywną metodą - ale skoro to działa to narazie ma niższy priorytet... :]

... chyba jednak nie taki niski :)
po ostatnich zmianach (https://github.com/mlesniew/elicznik/issues/3#issuecomment-1498835063) stwierdzam że przerabiam program na wersję "CSV-ONLY" ;)

aktualne prace prowadzę w branchu [csv](https://github.com/manio/elicznik-rs/tree/csv):
- scraper gotowy
- parser do napisania i przetestowania (czy aby napewno dane pociągnięte nową metodą za poprzednie miesiące pasują mi do tego co aktualnie mam w bazie)
